# Generated by Django 5.2.12 on 2026-03-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_approval', '0002_customer_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='current_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
